# API keys
google_api_key: "YOUR_GOOGLE_API_KEY"

# Agent configuration
agent_config:
  agent_type: "gemini"
  agent_name: "gemini-1.5-flash"

# File paths
data_paths:
  raw_dir: "data/raw/"
  processed_dir: "data/processed/"
  finetune_dataset_dir: "data/finetune_dataset/"
  cache_dir: ".cache/"
  
# Neo4j credentials
neo4j:
  uri: "neo4j://localhost:7687"
  user: "neo4j"
  password: "YOUR_NEO4J_PASSWORD" # <-- IMPORTANT: Change this to your Neo4j password
  database: "neo4j"
